### PR TITLE
Mirgated to v4

### PR DESCRIPTION
**Pull request by Equin**
its fork of #492 but with some changes:
 - added async functions with callbacks
 - removed serviceConnection as looks like v4 billing already doing same.
 - added simple retry connection logic
 - saving developer paylod locally as google removed such functionality. (will not be sent to playmarket)
 - some minor fixes
 - tried to follow original code style
 - subscriptions works pretty fine, but i did not changed code for purchases because i dont have ability to test purchases.
 
PS: was doing this changes to make my project work, hope someone can finish my work or point me in right direction=)
@serggl @showdpro

### CODE REVIEW

**Comment by serggl** [comment]
v2.0.0 was just pushed to maven central. 
README updated accordingly
Migration plan / breaking changes were listed [here](https://github.com/anjlab/android-inapp-billing-v3/blob/master/UPGRADING.md).

Good luck for everyone still planning to upgrade!

**Comment by moisoni97** [comment]
> > This was a great library that I have used in my apps but unfortunately, it wasn't updated by the original author @serggl (who knows what he's doing) and the new version just doesn't meet the code quality I expect. Sure, it works, but I want it to be perfect. At some point, I was interested to update this library myself but then I realized it would be much simpler to make a library from scratch and I ended up creating my own billing library. For obvious reasons, I won't post a direct link to my library here but if you are interested to migrate your app ASAP, check my profile. It's not a promo, the library is free and I don't get anything if you use it or not. I have created it in the first place for myself.
> 
> Hi, i saw your lib when i needed to update my project with v4 billing library, your lib not bad but its not support subscription upgrade and subscription cancel (it support, but as i can see it just opening google play page), and thats not what i need. So i decided to change current librarry for myself and help to upgrade it. Maybe someday someone can make it more cleaner so it will meet your code quality.

Don't get me wrong, if @serggl finally approved the pull request after all these months and changes, it means that now is all right and up to his standards which is good (he is a very skilled individual). I didn't follow the project in particular but I was speaking about the first pull request attempt which was in my opinion a big mess, not following the base code style, and was made in a more "barbaric way" just to work. That's why I said about code quality and the fact that it took a few months to finish really prove my point.

**Comment by ismailnurudeen** [comment]
Great Job @showdpro @Equin @serggl 👏🏾 👏🏾 👏🏾

**Comment by oceanox** [comment]
Thank you very much, great job! @showdpro @Equin @serggl 
- A question, we only have to update the version of the implements finally then?
From what I see, there are no more changes in the implementation of the library in our apps.

**Comment by qijaz221** [comment]
@oceanox There are some breaking changes, they are pretty simple and here's the migration guide: https://github.com/anjlab/android-inapp-billing-v3/blob/master/UPGRADING.md

**Comment by RozeKurhy** [comment]
Thank you very much!!!!!!!!!!! @showdpro @Equin @serggl

**Comment by doganmur** [comment]
Thank you very much, great job! @showdpro @Equin @serggl

**Comment by ysnsyhn** [comment]
Thanks a lot .@showdpro @Equin @serggl

Where is the "Give a cup of coffee" Button :)

**Pull request merged**
