### PR TITLE
load purchases in thread on service initialization

### PR DESCRIPTION
**Pull request by serggl**
would love to hear feedback here.
that should solve #164, #191, #195

### CODE REVIEW

**Comment by franciscofranco** [comment]
That seems good to me. I would run the AsyncTask in an executor instead of dropping it into the system pool. AsyncTaskCompat.execute(AsyncTask.class). If you don't want to have v4 dependency this is a good example: https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/library/src/com/davemorrissey/labs/subscaleview/SubsamplingScaleImageView.java#L1825

**Comment by serggl** [comment]
thanks for the suggestion @franciscofranco, but I prefer to keep code simple. And reliable 😉

**Comment by franciscofranco** [comment]
This is reliable. You can look into here: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/master/v4/java/android/support/v4/os/AsyncTaskCompat.java and https://github.com/futuresimple/android-support-v4/blob/master/src/honeycomb/android/support/v4/os/AsyncTaskCompatHoneycomb.java to see Google's solution. It's easy to apply on your code.

**Comment by serggl** [comment]
After reading some stackoverflow explanations, I don't believe we could win much on the performance side, so I still vote for the simplicity.

**Comment by chrisjenx** [comment]
I would vote to never ever use an AsyncTask, they do different things on different versions of Android, unless you want to make this API 14+ and always pass through a ExecutorPool, then do this using a ThreadedHandler.

**Pull request merged**
