### PR TITLE
 Migrated to androidx and Updated to Version 4 of Google in-App Payments

### PR DESCRIPTION
**Pull request by showdpro**
### Updated to Version 4 of Google in-App Payments
This fixes the warnings on developers' dashboard on Play Console  i.e.

> "_Action required: Please verify your publicly available APKs are updated to the latest version of the Play Billing Library. This includes any APK or App Bundle rolled out in production._"

The Implementation is pretty much the same as old library just add "bp.connect(this)" to the already existing codes and you are good to go, see sample app for case study. 
I have added intent data to the onActivityResult for those who will like to verify purchase Token on their server, please check the readMe for more information on this. 
This has been tested on 2 physical testing devices on Playstore and its working fine. Hope it helps
Cc: @serggl please review updates. 
Regards,
Somoye

### CODE REVIEW

**Comment by showdpro** [comment]
I have upgraded the anjlab to the latest version 4 of google in-app billing. I hope the pull request is accepted soon.
if anyone is interested in the alpha testing sample app, you can share your email so that i can add you as a tester on Playstore.

**Comment by serggl** [comment]
@showdpro can you please update source code to exclude file permission changes? Right now it's kind of hard to review...

**Comment by showdpro** [comment]
> @showdpro can you please update source code to exclude file permission changes? Right now it's kind of hard to review...

@serggl ok I will do the update and get back to you.

**Comment by showdpro** [comment]
> @showdpro can you please update source code to exclude file permission changes? Right now it's kind of hard to review...



> > @showdpro can you please update source code to exclude file permission changes? Right now it's kind of hard to review...
> 
> @serggl ok I will do the update and get back to you.

@serggl Done

**Comment by serggl** [comment]
@showdpro there is still a lot of `100644 → 100755` in the diff....

**Comment by serggl** [comment]
@showdpro and PR reports 166 commits, which makes me think you need to update your fork first before creating a pull request. Not sure, bu maybe you need follow [this guide](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) and then re-submit the PR?

I would love to review this then

**Comment by showdpro** [comment]
> @showdpro there is still a lot of `100644 → 100755` in the diff....

@serggl yes those are the diff in the BillingProcessor after the update

**Comment by showdpro** [comment]
> @showdpro and PR reports 166 commits, which makes me think you need to update your fork first before creating a pull request. Not sure, but maybe you need follow [this guide](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) and then re-submit the PR?
> 
> I would love to review this then

@serggl , I have actually followed the guide and my fork was in sync, i even tried to fetch from upstream but there was a message showing that i cant do that because mine is ahead of upstream by 166 commits. Maybe if i sent another pull from another branch will work. thanks.

**Comment by serggl** [comment]
conversation moved into https://github.com/anjlab/android-inapp-billing-v3/pull/492

**Pull request closed without merging**
