### PR TITLE
Issue 272. Added ability to include developer payload in updateSubscription() methods

### PR DESCRIPTION
**Pull request by autonomousapps**

### CODE REVIEW

**Comment by autonomousapps** [comment]
I can rebase it tomorrow if necessary.

**Comment by autonomousapps** [comment]
Rebased on the latest.

Since you approve, would you mind releasing a new version with this update once it gets merged? Thanks!

**Comment by serggl** [comment]
released as 1.0.40

**Comment by autonomousapps** [comment]
Awesome, thank you.

**Pull request merged**
