### PR TITLE
Add proguard rule

### PR DESCRIPTION
**Pull request by AllanWang**
I didn't see any documentation on proguard so I added the one rule from google's tutorial. I have tested it in my own project and it seems to work.

I'd also like to add some more documentation on certain methods, namely to make it clear what they return, whether they are async or not, whether they can be run on the ui thread, etc. That will be another PR though, but if I have your attention I'd like to perhaps verify a few things.

### CODE REVIEW

**Comment by serggl** [comment]
Well, I would actually prefer to document only proguard rules vs bundling them by default

**Comment by AllanWang** [comment]
@serggl I have removed the default file and added a line in the read me. Out of curiosity, what is the downside to bundling the rule with the release?

**Comment by serggl** [comment]
well,maybe Im just too wary about any 'default' proguard usage.
Can you explain how `consumerProguardFiles` will actually work?

**Comment by AllanWang** [comment]
@serggl the definitions in the consumer proguard file is essentially added to the user's proguard file if they build with proguard. Since this rule is required for everyone who minifies, it makes sense to bundle it with the library so they don't have to manually copy it. That's also why there's a default android proguard file and why you don't need to add your own lines for many libraries.

**Comment by serggl** [comment]
ok, then lets go with your original proposal with one addition: we need to explicitly document what proguard rules are going to be bundled with the library

**Comment by AllanWang** [comment]
@serggl I added the file back. That line is all I needed for the project to work, but if there are other cases involving reflection that I'm not aware of it should be added to the file as well

**Pull request merged**
