### PR TITLE
add extra checker method for one time purchase

### PR DESCRIPTION
**Pull request by MedetZhakupov**
Hi AnjLab, here is the brief explanation why I made those changes.
After having a meeting with google guys I found out that checking for "lab service" as you do [here](https://github.com/anjlab/android-inapp-billing-v3/blob/master/library/src/main/java/com/anjlab/android/iab/v3/BillingProcessor.java#L148-L152) is not enough. We have an use case when we have to check first whether the lab is supported or not. Depending on that our payment page will show Iab as a payment option if it's supported.

> Example:

 If the phone does not have sim card your method will return true since it's just checking for the existence of the package name but eventually lab service won't work because there is no sim card installed. 

I know that it's really rear case but we still want to cover it since we have more than 1 million active users worldwide. 

Lastly, I am proposing to have this extra method to make it more reliable no matter what are the circumstances are. If I need one-time purchase I will check for that, if I need subscription I will check for that. Please give a comment if you have any concern. By the way, great library, keep it up!

### CODE REVIEW

**Comment by serggl** [comment]
@MedetZhakupov this looks good. Additionally, can you please remove unrelated code formatting changes and add a notice to README?
Thanks!

**Comment by serggl** [comment]
Still looks odd..Why was the uploadArchives commented?

**Comment by MedetZhakupov** [comment]
Please ignore this last comment it happened accidentally. I will do proper one soon.

**Comment by MedetZhakupov** [comment]
@serggl Please have a look to my final commit and README change proposal. Thank you!

**Comment by serggl** [comment]
@MedetZhakupov dont see any README changes 🤔 
Also can you please rebase your branch against latest master code? Right now changelog in this PR shows some code which was 'added', but its actually present in master, for instance `Constants.java` changes

**Comment by MedetZhakupov** [comment]
@serggl I've rebased just know but seems like still have weird codes. Could you have a look, please? Maby it's not that crucial. Thank you!

**Comment by serggl** [comment]
@MedetZhakupov my only concern is that repo history should be clean. Would it be simpler for you to close this PR and open a new one, branched from the updated master?

**Comment by MedetZhakupov** [comment]
@serggl I was thinking about that too. Will do so. Thanks

**Pull request closed without merging**
