### PR TITLE
bumped to billing library v7 because of deadline

### PR DESCRIPTION
**Pull request by Cherdenko**
replaced setOldSkuPurchaseToken with setOldPurchaseToken as well as bumped dependencies

### CODE REVIEW

**Review by serggl — APPROVED** [review]
wonder why test suite was not run 🤔

**Comment by Cherdenko** [comment]
Not sure, quite weird. can you maybe try to manually run?

**Comment by marco97pa** [comment]
Thanks for all the work of who is trying hard to keep this important library alive @Cherdenko . There is any hope it will be available before the deadline? There isn't too much time left.

**Comment by serggl** [comment]
@Cherdenko v`2.2.0` was pushed to Maven Central. Thanks!

**Comment by Cherdenko** [comment]
@serggl ty for merging :)

**Pull request merged**
