### PR TITLE
fix: skip signature check if base64PublicKey is null

### PR DESCRIPTION
**Pull request by renedecandido**
If the license key is NULL the signature check is skipped (as stated in the readme file "You can pass NULL if you would like to skip this check")

### CODE REVIEW

**Comment by vitas** [comment]
without comment why that change is required, you should rather  use TextUtils.isEmpty(publicKey) for consistency and remove such check below in if statement for clean up

**Comment by renedecandido** [comment]
As described in the library's README.md you can pass NULL instead of the License Key to skip the purchase signature verification. In case of a NULL License Key the library returned false and broke the normal purchase flow which is not desired in case you are checking the signature on a server.

**Comment by serggl** [comment]
this is a fair pull request. Just give me some time to merge it

**Comment by serggl** [comment]
actually, I would like to move this check from `Security.verifyPurchase` to `BillingProcessor.verifyPurchaseSignature` method. And also this should be done with `TextUtils.isEmpty` like @vitas mentioned.

Would you mind to apply these changes?

**Pull request merged**
