### PR TITLE
Floating Point Math. Issue #124.

### PR DESCRIPTION
**Pull request by inktomi**
Created new long value for price, so that the price of a product is accessible without floating point errors for clients. 

Added parcelable for model objects which may need to be passed around between activities/fragments via bundles. 

Issue #124.

### CODE REVIEW

**Comment by serggl** [comment]
`double` to `Double` change looks good...probably...Not sure how sensitive this change would be for existing apps...
However, it looks like we need unit tests for the `Parcelable` stuff, otherwise there is no way to make sure it works. Agree?
And also, maybe you should split those 2 changes into 2 PRs?

**Comment by inktomi** [comment]
Sounds good. I'll update!

**Comment by inktomi** [comment]
Updated this PR to only include the Double / long change for SkuDetails. 

Will enter another with Parcelable and unit tests.

**Comment by inktomi** [comment]
Pull Request #133 adds back in the parcelable implementations, as well as android unit tests for each object.

**Pull request merged**
